services:
    app:
        container_name: app
        image: admin-store
        environment:
            HOST_URL: http://localhost
        ports:
            - "8000:80"
        depends_on:
            db:
                condition: service_healthy
        volumes:
            - storage:/var/www/html/storage/logs

    db:
        image: postgres
        container_name: postgres
        restart: always
        user: postgres
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        expose:
            - 5432
        healthcheck:
            test: [ "CMD", "pg_isready" ]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    db-data:
    storage:
