services:
    app:
        container_name: app
        image: admin-store
        depends_on:
            db:
                condition: service_healthy
        volumes:
            - "/var/www/html"
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    
    webserver:
        image: nginx
        working_dir: /var/www/html
        ports:
            - "9000:80"
        environment:
            - PHP_FPM=app
        volumes_from:
            - app:ro
        depends_on:
            - app
    
    db:
        image: postgres
        container_name: postgres
        restart: always
        user: postgres
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        expose:
            - 5432
        healthcheck:
            test: [ "CMD", "pg_isready" ]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    db-data: