services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        image: admin-store
        ports:
            - "8000:8000"
            - "2019:2019"
        volumes:
            - storage:/app/storage/app
            - ./:/app
        network_mode:
            docker_default
        environment:
            SUPERVISOR_PHP_COMMAND: "/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan octane:start --host=localhost --port=8000 --admin-port=2019 --https"
    
    db:
        image: postgres
        container_name: postgres
        restart: always
        user: postgres
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        expose:
            - 5432
        healthcheck:
            test: [ "CMD", "pg_isready" ]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    db-data:
    storage:
    app:
