services:
    app:
        container_name: app
        image: admin-store
        entrypoint: php artisan octane:frankenphp --workers=1 --max-requests=1
        ports:
            - "8000:8000"
        depends_on:
            db:
                condition: service_healthy
        volumes:
            - storage:/app/storage/app

    db:
        image: postgres
        container_name: postgres
        restart: always
        user: postgres
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        expose:
            - 5432
        healthcheck:
            test: [ "CMD", "pg_isready" ]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    db-data:
    storage:
    app:
