apiVersion: v1
kind: ConfigMap
metadata:
    name: dotfile-config
data:
    APP_NAME: "Admin Store"
    APP_ENV: 'production'
    APP_DEBUG: 'true'
    DEBUGBAR_ENABLED: 'false'
    APP_URL: '127.0.0.1'
    
    LOG_CHANNEL: 'stderr'
    LOG_DEPRECATIONS_CHANNEL: 'null'
    LOG_LEVEL: 'debug'

    DB_CONNECTION: 'pgsql'
    DB_HOST: "db-service"
    DB_USERNAME: "postgres"
    DB_PORT: "5432"
    DB_DATABASE: "e_store"
    
    MEMCACHED_HOST: '127.0.0.1'

    REDIS_HOST: '127.0.0.1'
    REDIS_PASSWORD: 'null'
    REDIS_PORT: '6379'
    
    BROADCAST_DRIVER: "log"
    CACHE_DRIVER: "file"
    FILESYSTEM_DISK: "public"
    QUEUE_CONNECTION: "sync"
    SESSION_DRIVER: "file"
    SESSION_LIFETIME: "120"
    
    MAIL_MAILER: "smtp"
    MAIL_HOST: "mailpit"
    MAIL_PORT: "1025"
    MAIL_FROM_ADDRESS: "hello@example.com"
    MAIL_FROM_NAME: "${APP_NAME}"
    MAIL_ENCRYPTION: 'tls'
    
    AWS_DEFAULT_REGION: 'us-east-1'
    AWS_BUCKET: 'e-store'
    AWS_USE_PATH_STYLE_ENDPOINT: 'true'
    AWS_ENDPOINT: 'https://192.168.0.89:9000'
    
    PUSHER_HOST: ""
    PUSHER_PORT: '443'
    PUSHER_SCHEME: 'https'
    PUSHER_APP_CLUSTER: 'mt1'

    VITE_APP_NAME: "${APP_NAME}"
    VITE_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"
    VITE_PUSHER_HOST: "${PUSHER_HOST}"
    VITE_PUSHER_PORT: "${PUSHER_PORT}"
    VITE_PUSHER_SCHEME: "${PUSHER_SCHEME}"
    VITE_PUSHER_APP_CLUSTER: "${PUSHER_APP_CLUSTER}"
    
