---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres-deployment
    labels:
        app: backend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: backend
    template:
        metadata:
            labels:
                app: backend
        spec:
            containers:
                -   name: postgres
                    image: postgres:latest
                    imagePullPolicy: Always
                    ports:
                        -   containerPort: 5432
                    env:
                        -   name: POSTGRES_DB
                            valueFrom:
                                configMapKeyRef:
                                    name: dotfile-config
                                    key: DB_DATABASE
                        -   name: POSTGRES_PASSWORD
                            valueFrom: 
                                secretKeyRef:
                                    name: dotfile-secret
                                    key: DB_PASSWORD
                        -   name: POSTGRES_USER
                            valueFrom:
                                configMapKeyRef:
                                    name: dotfile-config
                                    key: DB_USERNAME
                    volumeMounts:
                        -   mountPath: /var/lib/postgresql/data
                            name: db-storage
                -   name: adminer
                    image: adminer
                    imagePullPolicy: Always
                    ports:
                        -   containerPort: 8080
            volumes:
                -   name: db-storage
                    persistentVolumeClaim:
                        claimName: db-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: admin-store-deployment
    labels:
        app: admin-store
spec:
    replicas: 1
    selector:
        matchLabels:
            app: admin-store
    template:
        metadata:
            labels:
                app: admin-store
        spec:
            containers:
                -   name: admin-store
                    image: admin-store:latest
                    imagePullPolicy: Never
                    ports:
                        -   containerPort: 8000
                    envFrom:
                        -   configMapRef:
                                name: dotfile-config
                        -   secretRef:
                                name: dotfile-secret