---
apiVersion: v1
kind: Service
metadata:
    name: webapp-service
spec:
    type: LoadBalancer
    selector:
        app: admin-store
    ports:
        -   port: 8000
            targetPort: 8000
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
    name: db-service
spec:
    type: ClusterIP
    selector:
        app: backend
    ports:
        -   port: 5432
            targetPort: 5432
            protocol: TCP
            name: postgres-db
---
apiVersion: v1
kind: Service
metadata:
    name: adminer-service
spec:
    type: LoadBalancer
    selector:
        app: backend
    ports:
        -   port: 8181
            targetPort: 8080
            protocol: TCP
            name: adminer
