apiVersion: v1
kind: Service
metadata:
    name: postgres-service
    namespace: staging
spec:
    selector:
        app: postgres
    ports:
        -   protocol: TCP
            port: 5432
            targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
    name: webapp-service
    namespace: staging
spec:
    type: LoadBalancer
    selector:
        app: admin-store
    ports:
        -   port: 8100
            targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
    name: adminer-service
    namespace: staging
spec:
    type: LoadBalancer
    selector:
        app: adminer
    ports:
        -   port: 8180
            targetPort: 8080
